import { randomUUID } from 'node:crypto';
import { createFallbackProvider } from './ai/fallback.js';
export type ProviderStatus='QUEUED'|'PROCESSING'|'COMPLETED'|'FAILED'|'CANCELLED';
export interface AIProvider { generateTryOn(input:{productImage:string;modelImage:string;faceImage?:string;category?:string;prompt:string;background:'original'|'studio'|'lifestyle'}):Promise<{providerJobId:string}>;getGenerationStatus(id:string):Promise<{status:ProviderStatus;resultUrl?:string;errorCode?:string;provider?:string;attempts?:string[]}>;cancelGeneration(id:string):Promise<void>; }
const demoSvg='data:image/svg+xml;base64,'+Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="720" height="900"><rect width="100%" height="100%" fill="#f0ebff"/><circle cx="360" cy="220" r="105" fill="#c99476"/><path d="M210 850V455c0-105 300-105 300 0v395" fill="#473c8f"/><text x="360" y="820" text-anchor="middle" fill="white" font-family="Arial" font-size="25">DEMO TRY-ON</text></svg>`).toString('base64');
const jobs=new Map<string,{started:number;cancelled:boolean}>();
export class MockAIProvider implements AIProvider {async generateTryOn(){const providerJobId=randomUUID();jobs.set(providerJobId,{started:Date.now(),cancelled:false});return{providerJobId};}async getGenerationStatus(id:string){const j=jobs.get(id);if(!j)return{status:'FAILED' as const};if(j.cancelled)return{status:'CANCELLED' as const};const age=Date.now()-j.started;if(age<1200)return{status:'QUEUED' as const};if(age<4200)return{status:'PROCESSING' as const};return{status:'COMPLETED' as const,resultUrl:demoSvg};}async cancelGeneration(id:string){const j=jobs.get(id);if(j)j.cancelled=true;}}
type FashnResponse={id?:string;status?:string;output?:string[]|{images?:string[]};error?:string};
export class FashnAIProvider implements AIProvider {private key=process.env.FASHN_API_KEY;private headers(){if(!this.key)throw new Error('FASHN_API_KEY is required when AI_PROVIDER=fashn.');return{'Content-Type':'application/json','Authorization':`Bearer ${this.key}`};}async generateTryOn(input:Parameters<AIProvider['generateTryOn']>[0]){const response=await fetch('https://api.fashn.ai/v1/run',{method:'POST',headers:this.headers(),body:JSON.stringify({model_name:'tryon-max',inputs:{model_image:input.modelImage,product_image:input.productImage,face_reference:input.faceImage,prompt:input.prompt}}),signal:AbortSignal.timeout(30_000)});const body=await response.json() as FashnResponse;if(!response.ok||!body.id)throw new Error(body.error||'FASHN could not start the generation.');return{providerJobId:body.id};}async getGenerationStatus(id:string):Promise<{status:ProviderStatus;resultUrl?:string;errorCode?:string}>{const response=await fetch(`https://api.fashn.ai/v1/status/${encodeURIComponent(id)}`,{headers:this.headers(),signal:AbortSignal.timeout(20_000)});const body=await response.json() as FashnResponse;if(!response.ok)return{status:'FAILED',errorCode:body.error||'PROVIDER_ERROR'};if(body.status==='completed'){const output=Array.isArray(body.output)?body.output[0]:body.output?.images?.[0];return output?{status:'COMPLETED',resultUrl:output}:{status:'FAILED',errorCode:'EMPTY_RESULT'};}if(body.status==='failed')return{status:'FAILED',errorCode:body.error||'PROVIDER_FAILED'};return{status:body.status==='in_queue'||body.status==='starting'?'QUEUED':'PROCESSING'};}async cancelGeneration(){/* Provider has no documented cancellation endpoint. */}}
export const provider:AIProvider=process.env.AI_PROVIDER==='mock'?new MockAIProvider():process.env.AI_PROVIDER==='fashn'?new FashnAIProvider():createFallbackProvider();
