import { type ProductCandidate, categoryFromText } from '@tryon/shared';
const absolute=(url:string)=>{try{return new URL(url,location.href).href}catch{return undefined}};
const price=(text:string)=>{const m=text.match(/(?:₹|\$|€|£)\s?([\d,.]+)/);return m?Number(m[1].replace(/,/g,'')):undefined};
const imageOK=(s:string)=>s && !/logo|icon|avatar|sprite|banner|data:image/i.test(s);
const isSearchPage=()=>{const url=new URL(location.href);return /(^|\.)amazon\./i.test(url.hostname)&&(url.pathname==='/s'||url.searchParams.has('k')||url.searchParams.has('field-keywords'));};
function structured():ProductCandidate[]{const found:ProductCandidate[]=[];document.querySelectorAll('script[type="application/ld+json"]').forEach(s=>{try{const walk=(x:any)=>{if(Array.isArray(x))return x.forEach(walk);if(!x||typeof x!=='object')return;if(x['@type']==='Product'||(Array.isArray(x['@type'])&&x['@type'].includes('Product'))){const imgs=(Array.isArray(x.image)?x.image:[x.image]).map((u:any)=>typeof u==='string'?absolute(u):u?.url&&absolute(u.url)).filter(Boolean) as string[];const offer=Array.isArray(x.offers)?x.offers[0]:x.offers; if(imgs.length)found.push({id:crypto.randomUUID(),title:x.name||document.title,brand:typeof x.brand==='string'?x.brand:x.brand?.name,description:x.description,price:Number(offer?.price)||undefined,currency:offer?.priceCurrency,productUrl:absolute(x.url)||location.href,imageUrls:imgs,category:categoryFromText(`${x.name} ${x.category||''}`),confidence:.98,source:'jsonld'});}Object.values(x).forEach(walk)};walk(JSON.parse(s.textContent||'{}'))}catch{}});return found}
function metadata():ProductCandidate[]{if(isSearchPage())return[];const get=(p:string)=>document.querySelector(`meta[property="${p}"],meta[name="${p}"]`)?.getAttribute('content')||'';const img=absolute(get('og:image'));if(!img)return[];const title=get('og:title')||document.title;return[{id:crypto.randomUUID(),title,description:get('og:description')||undefined,productUrl:location.href,imageUrls:[img],category:categoryFromText(title),confidence:.7,source:'og'}]}
function dom():ProductCandidate[]{const out:ProductCandidate[]=[];const imgs=[...document.images].filter(i=>i.width>120&&i.height>120&&imageOK(i.currentSrc||i.src)).slice(0,24);for(const img of imgs){const card=img.closest('article,li,[class*="product" i],[class*="card" i]')||img.parentElement;const text=(card?.textContent||'').replace(/\s+/g,' ').trim();const title=img.alt||card?.querySelector('h1,h2,h3,h4')?.textContent?.trim()||text.slice(0,90)||'Product';out.push({id:crypto.randomUUID(),title,price:price(text),currency:text.includes('₹')?'INR':text.includes('$')?'USD':undefined,productUrl:(img.closest('a') as HTMLAnchorElement)?.href||location.href,imageUrls:[img.currentSrc||img.src],category:categoryFromText(title),confidence:img.alt?0.55:0.38,source:'dom'});}return out}
function scan(){const raw=[...structured(),...metadata(),...dom()];const seen=new Set<string>();return raw.filter(p=>{const key=(p.productUrl||p.imageUrls[0]).split('?')[0];if(seen.has(key))return false;seen.add(key);return true}).sort((a,b)=>b.confidence-a.confidence).slice(0,16)}
chrome.runtime.onMessage.addListener((m,_,reply)=>{if(m.type==='SCAN_PRODUCTS'){reply({products:scan(),url:location.href,title:document.title});}return true;});
