import React,{useEffect,useMemo,useState} from 'react'; import {createRoot} from 'react-dom/client'; import {Check,ChevronLeft,ImagePlus,ScanSearch,Trash2,Download,History} from 'lucide-react'; import type {ProductCandidate} from '@tryon/shared'; import './styles.css';
import { CameraCapture, ImageCrop } from './Capture';
import { LayeredText, TangleFooter } from './HomeArt';
import Avatar from './Avatar';
import LoadingBottle from './LoadingBottle';
import { InfiniteRibbon } from './InfiniteRibbon';
import './glass.css';
import './home-layout.css';
import { captureShoppingPage } from './screenshot';
import { scanActivePage } from './scan';
const API='http://localhost:8787/api'; type Profile={id:string;name:string;assets:{id:string;type:string;storageKey:string}[]};
const previewUrl=(url:string)=>url.startsWith('https://')?`${API}/image-proxy?url=${encodeURIComponent(url)}`:url;
async function api(path:string,options?:RequestInit){const r=await fetch(API+path,{headers:{'Content-Type':'application/json',...(options?.headers||{})},...options});const j=await r.json();if(!j.success)throw new Error(j.error.message);return j.data;}
const assetInfo=[['fullBody','Full body','Stand upright, face the camera, and keep your entire body visible.'],['upperBody','Upper body','Keep shoulders and torso front-facing in good light.'],['lowerBody','Lower body','Keep waist to feet clearly visible with minimal occlusion.'],['foot','Foot / shoe','Photograph your foot clearly from a natural angle.'],['face','Face','Use a well-lit, front-facing image with no heavy filters.']] as const;
function GlassFilter(){return <svg className="glass-filter" aria-hidden="true"><defs><filter id="container-glass" x="0%" y="0%" width="100%" height="100%" colorInterpolationFilters="sRGB"><feTurbulence type="fractalNoise" baseFrequency="0.05 0.05" numOctaves="1" seed="1" result="turbulence"/><feGaussianBlur in="turbulence" stdDeviation="2" result="blurredNoise"/><feDisplacementMap in="SourceGraphic" in2="blurredNoise" scale="70" xChannelSelector="R" yChannelSelector="B" result="displaced"/><feGaussianBlur in="displaced" stdDeviation="4" result="finalBlur"/><feComposite in="finalBlur" in2="finalBlur" operator="over"/></filter></defs></svg>}
function App(){const [screenshot,setScreenshot]=useState(''),[camera,setCamera]=useState(false),[cameraPhoto,setCameraPhoto]=useState('');const [profile,setProfile]=useState<Profile|null>(null),[name,setName]=useState(''),[products,setProducts]=useState<ProductCandidate[]>([]),[selected,setSelected]=useState<ProductCandidate|null>(null),[selectedImage,setSelectedImage]=useState(''),[background,setBackground]=useState<'original'|'studio'|'lifestyle'>('original'),[view,setView]=useState<'home'|'profile'|'products'|'result'|'history'>('home'),[busy,setBusy]=useState(''),[job,setJob]=useState<any>(null),[result,setResult]=useState<any>(null),[error,setError]=useState(''); const completeness=useMemo(()=>profile?Math.round(profile.assets.length/5*100):0,[profile]);
const refresh=async()=>{try{setProfile(await api('/profile'))}catch(e){setError((e as Error).message)}};useEffect(()=>{refresh()},[]); const run=async(fn:()=>Promise<void>)=>{setError('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy('')}};
const scan=()=>run(async()=>{setBusy('Scanning this page…');const r=await scanActivePage();setSelected(null);setSelectedImage('');setProducts(r.products||[]);setView('products');});
const create=()=>run(async()=>{setBusy('Creating profile…');setProfile(await api('/profile',{method:'POST',body:JSON.stringify({name})}));setView('profile')});
const upload=(type:string,file?:File)=>run(async()=>{if(!file)return;if(!/^image\/(jpeg|png|webp)$/.test(file.type)||file.size>8*1024*1024)throw new Error('Use a JPEG, PNG, or WebP under 8 MB.');setBusy('Uploading photograph…');const f=new FormData();f.append('type',type);f.append('file',file);const r=await fetch(API+'/profile/assets',{method:'POST',body:f});const j=await r.json();if(!j.success)throw new Error(j.error.message);await refresh();});
const generate=async(personImage?:string)=>{if(!selected||!selectedImage)throw new Error('Select clothing first.');setBusy('Preparing your try-on…');try{const p=await api('/products/resolve',{method:'POST',body:JSON.stringify(selected)});const j=await api('/tryon',{method:'POST',body:JSON.stringify({productId:p.id,imageUrl:selectedImage,background,personImage:personImage||cameraPhoto||undefined})});setCameraPhoto('');setResult(null);setJob(j);setView('result');}finally{setBusy('')}};
const start=()=>run(()=>generate());
const snip=()=>run(async()=>{setScreenshot(await captureShoppingPage());setCamera(false);});

useEffect(()=>{if(!job?.id)return;const timer=setInterval(async()=>{try{const j=await api('/tryon/'+job.id);setJob(j);if(j.status==='COMPLETED'){setResult(j.result);clearInterval(timer)}if(['FAILED','CANCELLED'].includes(j.status)){setError(j.status==='FAILED'?'Generation failed. Check the local CatVTON service or configure your cloud fallback keys.':'Generation cancelled.');clearInterval(timer)}}catch(e){setError((e as Error).message);clearInterval(timer)}},1100);return()=>clearInterval(timer)},[job?.id]);
return <main className={view==='home'?'home-screen':undefined}><GlassFilter/><header><button className="brand" onClick={()=>setView('home')}><Avatar small/> WearWise</button><button aria-label="History" onClick={()=>setView('history')}><History size={18}/></button></header>{error&&<div className="error">{error}<button onClick={()=>setError('')}>×</button></div>}{busy&&<div className="toast"><LoadingBottle compact/> {busy}</div>}
{view==='home'&&<section className="hero"><div className="hero-intro"><div className="hero-avatar"><Avatar/></div><LayeredText/></div><div className="ribbons"><InfiniteRibbon>Your private AI shopping companion uses a reusable digital body profile to visualize selected items.</InfiniteRibbon><InfiniteRibbon reverse>Your private AI shopping companion uses a reusable digital body profile to visualize selected items.</InfiniteRibbon></div>{profile?<div className="home-controls"><div className="profile-chip"><Check/> {profile.name} · {completeness}% ready</div><button className="primary" onClick={scan}><ScanSearch/> Scan this page</button><button className="link" onClick={()=>setView('profile')}>Manage profile</button></div>:<div className="home-create"><input placeholder="Your profile name" value={name} onChange={e=>setName(e.target.value)}/><button className="primary" disabled={!name.trim()} onClick={create}>Create your profile</button></div>}<TangleFooter/></section>}
{view==='profile'&&<section><button className="back" onClick={()=>setView('home')}><ChevronLeft/> Back</button><h2>Digital body profile</h2><p className="muted">{profile?.name} · {completeness}% complete. Add photos only as required for the category you want to try.</p><div className="progress"><i style={{width:completeness+'%'}}/></div>{assetInfo.map(([type,label,help])=>{const asset=profile?.assets.find(a=>a.type===type);return <article className="asset" key={type}><div className="asset-icon">{asset?<Check/>:<ImagePlus/>}</div><div><b>{label}</b><small>{help}</small>{asset&&<small className="done">Uploaded securely</small>}</div><label className="outline">{asset?'Replace':'Add'}<input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>upload(type,e.target.files?.[0])}/></label>{asset&&<button aria-label={'Delete '+label} onClick={()=>run(async()=>{setBusy('Deleting photograph…');await api('/profile/assets/'+asset.id,{method:'DELETE'});await refresh()})}><Trash2 size={16}/></button>}</article>})}<button className="danger" onClick={()=>{if(confirm('Delete profile and all private photos/results?'))run(async()=>{await api('/profile',{method:'DELETE'});setProfile(null);setView('home')})}}>Delete profile</button></section>}
{view==='products'&&<section><button className="back" onClick={()=>setView('home')}><ChevronLeft/> Back</button><h2>Products on this page</h2><p className="muted">{products.length?`Detected ${products.length} likely products. Choose one to inspect.`:'No products found. Open a product or category page and try again.'}</p><div className="scan-actions"><button className="outline scan" onClick={scan}><ScanSearch size={16}/> Scan again</button><button className="outline" onClick={snip}>Select image</button><button className="outline" onClick={()=>{setCamera(true);setScreenshot('')}}>Camera</button></div>{screenshot&&<ImageCrop screenshot={screenshot} close={()=>setScreenshot('')} select={(image,category)=>{const item:ProductCandidate={id:crypto.randomUUID(),title:'Selected clothing',category,imageUrls:[image],confidence:1,source:'image-analysis'};setProducts(p=>[item,...p]);setSelected(item);setSelectedImage(image);setScreenshot('');}}/>}{camera&&<CameraCapture close={()=>setCamera(false)} actionLabel={selected?'Use photo & try on':'Use this photo'} usePhoto={async image=>{if(selected)await generate(image);else setCameraPhoto(image);}}/>} {cameraPhoto&&<p className="muted" role="status">Camera photo ready. Select clothing below, then click Try on. <button className="outline" onClick={()=>setCameraPhoto('')}>Discard photo</button></p>}<div className="cards">{products.map(p=><button className={'product '+(selected?.id===p.id?'selected':'')} key={p.id} onClick={()=>{setSelected(p);setSelectedImage(p.imageUrls[0])}}><img src={previewUrl(p.imageUrls[0])} alt=""/><span><b>{p.title}</b><small>{p.price!==undefined?`${p.currency==='INR'?'₹':p.currency==='USD'?'$':''}${p.price}`:'Price unavailable'} · {p.category||'category unknown'}</small><em>{Math.round(p.confidence*100)}% match</em></span></button>)}</div>{selected&&<div className="choices"><p className="muted">Clothing uses local CatVTON first. If cloud fallback is enabled, photos may be sent to Gemini or OpenAI and charges may apply. Shoes, jewellery and scene changes require a cloud provider.</p><b>Product image</b><div className="thumbs">{selected.imageUrls.map(url=><button className={selectedImage===url?'active':''} key={url} onClick={()=>setSelectedImage(url)}><img src={previewUrl(url)} alt="Product view"/></button>)}</div><label>Presentation<select value={background} onChange={e=>setBackground(e.target.value as any)}><option value="original">Original background</option><option value="studio">Neutral studio</option><option value="lifestyle">Lifestyle background</option></select></label></div>} {selected&&<div className="bottom"><div><b>{selected.title}</b><small>Selected image and presentation are sent to the provider.</small></div><button className="primary" disabled={Boolean(busy)} onClick={start}>Try on</button></div>}</section>}
{view==='result'&&<section><button className="back" onClick={()=>{setJob(null);setResult(null);setView('products')}}><ChevronLeft/> Products</button>{!result?<div className="generating"><LoadingBottle/><h2>{job?.status==='QUEUED'?'Preparing your profile…':'Generating your try-on…'}</h2><p>We’re preserving product details and your profile characteristics. Provider: {job?.provider || 'preparing images'}.</p><button className="outline" onClick={()=>run(async()=>{if(job?.id)await api('/tryon/'+job.id+'/cancel',{method:'POST',body:'{}'});setJob(null);setView('products')})}>Cancel / back to products</button></div>:<><h2>Your virtual try-on</h2><img className="result" src={'http://localhost:8787'+result.url} alt="Generated virtual try-on"/><p className="muted">{selected?.title} · {profile?.name}</p><div className="actions"><a className="primary" href={'http://localhost:8787'+result.url} download="wearwise-tryon.svg"><Download/> Download</a><button className="outline" onClick={()=>{setResult(null);setJob(null);setView('products')}}>Try another</button></div></>}</section>}
{view==='history'&&<HistoryView back={()=>setView('home')} run={run}/>}</main>}
function HistoryView({back,run}:{back:()=>void;run:(f:()=>Promise<void>)=>void}){const [items,setItems]=useState<any[]>([]);const load=()=>run(async()=>setItems(await api('/results')));useEffect(()=>{load()},[]);return <section><button className="back" onClick={back}><ChevronLeft/> Back</button><h2>Result history</h2>{!items.length?<p className="empty">Your saved try-ons will appear here.</p>:items.map(x=><article className="history" key={x.id}><img src={'http://localhost:8787'+x.url} alt=""/><div><b>{x.product.title}</b><small>{x.product.category||'Product'} · {new Date(x.createdAt).toLocaleDateString()}</small></div><button onClick={()=>run(async()=>{await api('/results/'+x.id,{method:'DELETE'});load()})}><Trash2 size={16}/></button></article>)}</section>}; createRoot(document.getElementById('root')!).render(<App/>);
